version: '2'
services:
    web:
        image: nginx:alpine
        ports:
            - 84:80
        volumes:
            - ./code:/code
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
            - db
        container_name: demo3_web
    php:
        build: build/php
        volumes:
            - ./code:/code
        environment:
            - POSTGRES_USER=stcusr
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=demo3
        links:
            - db
        container_name: demo3_php
    db:
        image: postgres:alpine
        volumes:
            - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            - POSTGRES_USER=stcusr
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=demo3
        container_name: demo3_db
