version: '2'
services:
    php:
        build:
            context: "build/php"
            args:
                - http_proxy=${HTTP_PROXY}
                - https_proxy=${HTTP_PROXY}
                - HTTP_PROXY=${HTTP_PROXY}
                - HTTPS_PROXY=${HTTP_PROXY}
